name: nextstrain
channels:
  - bioconda
  - defaults
dependencies:
  - boto3=1.7.45
  - dropbox=5.2.1
  - fasttree=2.1.10
  - ipykernel=4.8.2
  - ipython=6.4.0
  - iqtree=1.5.5
  - jupyter_core=4.4.0
  - mafft=7.313
  - matplotlib=2.2.2
  - ncurses=6.1
  - numpy=1.14.5
  - pip
  - python=3.6.5
  - raxml=8.2.10
  - requests=2.14.2
  - scipy=1.1.0
  - sqlite=3.24.0
  - vcftools
  - wheel
  - pip:
    - biopython==1.73
    - cvxopt==1.1.9
    - drmaa==0.7.8
    - future==0.16.0
    - nextstrain-augur==4.0.0
    - nextstrain-cli==1.10.1
    - pandas==0.23.4
    - phylo-treetime==0.5.5
    - pip==19.0.3
    - rethinkdb==2.3.0.post6
    - seaborn==0.9.0
    - snakemake==5.3.0
